import typescript from '@rollup/plugin-typescript';

const banner = `// Autogenerated File
var ctx = this;
`

export default {
  input: 'src/index.ts',
  output: {
    dir: 'output',
    format: 'iife',
    banner
  },
  context: "ctx",
  plugins: [typescript()],
};